const PF = import.meta.env.VITE_APP_PUBLIC_FOLDER

export const Users = [
    {
      id:1,
      profilePicture: PF + "person/1.jpeg",
      username: "Deepak",
    },
    {
      id:2,
      profilePicture:PF + "person/2.jpeg",
      username: "Akash",
    },
    {
      id:3,
      profilePicture: PF +"person/3.jpeg",
      username: "Alex ",
    },
    {
      id:4,
      profilePicture:PF + "person/4.jpeg",
      username: "Rohit Hawks",
    },
    {
      id:5,
      profilePicture:PF + "person/5.jpeg",
      username: "Rahul",
    },
    {
      id:6,
      profilePicture: PF +"person/6.jpeg",
      username: "vijay",
    },
    {
      id:7,
      profilePicture:PF + "person/7.jpeg",
      username: "vinay",
    },
    {
      id:8,
      profilePicture:PF + "person/8.jpeg",
      username: "Vivek",
    },
    {
      id:9,
      profilePicture:PF + "person/9.jpeg",
      username: "Sivam",
    },
    {
      id:10,
      profilePicture:PF + "person/10.jpeg",
      username: "Monu",
    },
  ];

  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "post/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "post/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "post/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "post/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "post/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];